name: rManager
version: 3.2.2
main: com.ReanKR.rManager.rManager
author: ReanKR
description: To provide convenient functions in the REAN SERVER

commands:
  rm:
    description: §erManager Main command

permissions:
  rmanager.*:
    description: rManager와 관련한 모든 권한을 사용할 수 있습니다.
    default: false
  rmanager.view:
    description: rManager 도움말을 볼 수 있는 권한입니다.
    default: true
  myteleport.teleport.use:
    description: 텔레포트 기능을 사용할 수 있는 권한입니다.
    default: false
  myteleport.teleport.deny:
    description: 텔레포트를 자동 거부할 수 있는 권한입니다.
    default: false
  myteleport.teleport.world:
    description: 특정한 월드에서 텔레포트를 자동 거부할 수 있는 권한입니다.
    default: OP
  myteleport.teleport.bypass:
    description: 텔레포트를 할 때 금지된 월드 이동의 제한이 없고 거부된 플레이어에게도 접근할 수 있는 권한입니다.
    default: false
  customplayerwarp.warp:
    description: 워프를 사용할 수 있습니다.
    default: false
  customplayerwarp.setwarp:
    description: 개인 워프를 지정할 수 있습니다.
    default: false
  customplayerwarp.delwarp:
    description: 지정한 개인 워프를 삭제할 수 있습니다.
    default: false
  customplayerwarp.amount:
    description: 개인 워프 지정 갯수를 조작할 수 있는 권한입니다.
    default: false
  customplayerwarp.unlimited:
    description: 개인 워프 지정 갯수에 제한이 없습니다.
    default: false